### ISSUE TITLE
google/protobuf -> gogo/protobuf

### ISSUE THREAD

**Issue by LXY1226** [Mrs4s/MiraiGo#101]
speed++
size+
已经讨论过了，在这写点记录
gogo的protobuf有四种，其中
--gofast_out 需要换包名，+4M
--gogofast_out 需要换包名并改动现有代码，+3M
--gogofaster_out 需要换包名并把指针全部解引用，+2M，目前我那bot用的这，好像有变快但是内存没啥区别..
--gogoslick_out 同上一个，+4M

```
# find -name *.proto | xargs -I {} ./proto.sh {}
protoc --gogofaster_out=`dirname $1` $1
```
👆批量regen，也许可以扔到actions（大概率不用

**Comment by Mrs4s** [comment]
考虑到gocq的文件大小, 可能需要从其他地方优化
我目前还是尽量保证gocq小于20M...

**Comment by LXY1226** [comment]
refer to https://github.com/LXY1226/MiraiGo/tree/gogo/protobuf

**Comment by LXY1226** [comment]
fixed in RomiChan/Protobuf
