### ISSUE TITLE
是否增加百变气泡功能

### ISSUE THREAD

**Issue by tengfeilong** [Mrs4s/MiraiGo#103]
是否增加百变气泡功能

**Comment by sam01101** [comment]
惨, 没人回复
首先, 这个功能没有任何意义, 属于娱乐用
所以会支持, 但优先度较低

会首先首先气泡ID获取等先要条件, 所谓的百变气泡我不懂, 可能是随机气泡吧

那么会不会风控我不清楚, 毕竟没实际测试过, 但我这里提醒你别滥用
