### ISSUE TITLE
tts的解密方法是否有其他语言的？

### ISSUE THREAD

**Issue by Beattheend** [Mrs4s/MiraiGo#126]
大佬，感谢你的奉献，我最近抓包发现QQ语音的朗读挺有意思的感觉还带感情？但似乎是加密的。看了你的代码有解密的方法，但我不会go语言，能说下这是什么操作吗？我对qq协议也有兴趣

**Comment by sam01101** [comment]
等下, `Go lang`不是最容易看的语言吗?

**Comment by Mrs4s** [comment]
TTS接口本身并没有加密, 只是数据格式比较特殊.
可以参考
https://github.com/Mrs4s/MiraiGo/blob/c4288bd213f34f57dd12ce0e1ff29e5f72c604bb/client/tts.go#L20-L49
https://github.com/Mrs4s/MiraiGo/blob/c4288bd213f34f57dd12ce0e1ff29e5f72c604bb/client/tts.go#L23

**Comment by Beattheend** [comment]
> 等下, `Go lang`不是最容易看的语言吗?

害，流下了没有技术的眼泪！

**Comment by Beattheend** [comment]
> TTS接口本身并没有加密, 只是数据格式比较特殊.
> 可以参考
> https://github.com/Mrs4s/MiraiGo/blob/c4288bd213f34f57dd12ce0e1ff29e5f72c604bb/client/tts.go#L20-L49
> 
> 
> https://github.com/Mrs4s/MiraiGo/blob/c4288bd213f34f57dd12ce0e1ff29e5f72c604bb/client/tts.go#L23

太感谢了，谢谢。
