### ISSUE TITLE
希望增加网页临时会话回复功能

### ISSUE THREAD

**Issue by liliangshan** [Mrs4s/MiraiGo#142]
在收到 pMsg.Head.GetMsgType() == 141 && pMsg.Head.GetC2CCmd() == 11 时，回复消息提示需要加好友，但是在手机上和电脑端都可以回复不需要加好友，建议在收到这个类型的消息后可以回复，谢谢。
![image](https://user-images.githubusercontent.com/25602657/113511638-61e41200-9593-11eb-92d1-c83f10f6e686.png)
黑框中是我自己加的，已经可以收到临时会话的消息了。

**Comment by sam01101** [comment]
#132 
![image](https://user-images.githubusercontent.com/25792361/113511772-3281d500-9594-11eb-90af-de13fe7334b7.png)
我努力过了, 但被咕了
![image](https://user-images.githubusercontent.com/25792361/113511796-49c0c280-9594-11eb-80eb-99861fa1dd62.png)

![image](https://user-images.githubusercontent.com/25792361/113511800-4e857680-9594-11eb-9308-b30aa0e0d08b.png)

一个回头就是29天

**Comment by liliangshan** [comment]
哎，你有办法能让它不需要加好友就能发出去吧，按理说群的可以发，这个也应该可以，我试了各种办法就是需要加好友，哎

**Comment by Mrs4s** [comment]
这个之前做了一半 主要是比较难测试 没做下去

**Comment by liliangshan** [comment]
在现有的代码上调整可以实现回复么？我试了下怎么回复都是要提示加好友，或者您说个方案我看下能不能自己改下，谢谢

**Comment by liliangshan** [comment]
测试在 https://shang.qq.com/v3/widget.html 上开通临时会话，然后找个没加好友的发起会话就可以测试了啊

**Comment by sam01101** [comment]
这个不容易触发，所以才能测试

**Comment by Mrs4s** [comment]
没多的号了

**Comment by Mrs4s** [comment]
已支持
