### ISSUE TITLE
[bug] 记得添加刷新session

### ISSUE THREAD

**Issue by sam01101** [Mrs4s/MiraiGo#143]
https://github.com/Mrs4s/go-cqhttp/issues/798

**Comment by Mrs4s** [comment]
这是一个特殊情况, 在初始化的时候就掉线了, 优先度不高, 暂时不处理.

**Comment by sam01101** [comment]
![image](https://user-images.githubusercontent.com/25792361/113693240-fc159880-9700-11eb-96b5-a5a5b2f8151f.png)

**Comment by sam01101** [comment]
问题挺多的
