### ISSUE TITLE
net issues

### ISSUE THREAD

**Issue by Ink-33** [Mrs4s/MiraiGo#155]
以下问题均在调试滑块扫描二维码登录时检出

## 问题一
https://github.com/Mrs4s/MiraiGo/blob/8f474db6a37ed349483d758e74ce4197e090143f/client/client.go#L1026-L1040
https://github.com/Mrs4s/MiraiGo/blob/8f474db6a37ed349483d758e74ce4197e090143f/client/client.go#L932-L947
如图所示，当调用`sendAndWait`时如果出现`session expired`就会因收不到包而超时退出
![image](https://user-images.githubusercontent.com/51873347/116612038-a2a03280-a969-11eb-8330-5f9a6aa90acc.png)

## 问题二
https://github.com/Mrs4s/MiraiGo/blob/b66d8a9a951e7a64ed65cc3f9198853d4903cd44/client/client.go#L979-L993
若
``` go
if errors.Is(err, packets.ErrSessionExpired) || errors.Is(err, packets.ErrPacketDropped) { 
 	c.Disconnect() 
 	go c.dispatchDisconnectEvent(&ClientDisconnectedEvent{Message: "session expired"}) 
	c.Connect()
 	continue 
 } 
```
则能暴力解决问题一。但需要等待接近15秒才能获取到二维码。且`quickReconnect`返回register error时会打断`netLoop`，导致正常的`wtlogin.trans_emp`被打断，程序也不退出。
![image](https://user-images.githubusercontent.com/51873347/116611825-61a81e00-a969-11eb-965d-9d36659e85e6.png)

复现方法：滑块选择使用二维码。即使第一次成功，重启程序后必定失败

**Comment by Ink-33** [comment]
![image](https://user-images.githubusercontent.com/51873347/116612873-9cf71c80-a96a-11eb-9fea-47d1ad1c70c5.png)
问题二补充

**Comment by sam01101** [comment]
地铁 老人 手机.jpg
