### ISSUE TITLE
无法正常回复转发后的分享卡片？

### ISSUE THREAD

**Issue by povsister** [Mrs4s/MiraiGo#159]
### 前言
手机QQ通过其他App向好友分享一个链接，经过观察，其消息格式为
[LightAppElement]

LightAppElement是一段 JSON 数据，包含了jumpURL，以及 descr等等一系列必要信息

### 现象
第一次分享后，记此分享卡片的消息ID为 A
回复该分享卡片，ReplyElement的ReplySeq字段被正确设置为A

转发该分享卡片，此时消息ID变为 B
经过观察，转发后的消息格式为 [TextElement, LightAppElement]，但实际内容不变
其中TextElement代表一个Fallback msg，例如：”[分享] xxxx   请使用最新版手机QQ查看消息"

回复转发后的卡片，此时ReplyElement的ReplySeq字段却不是B，而是一个负数？
这样导致我无法定位到回复的消息原文究竟是什么

是我对功能理解有问题还是bug ？

### 实例

```
// 第一次分享卡片
Message {
  ID=47489
  Elems=[LightAppElement]
}

// 回复上面的卡片
Message {
  ID=....
  Elems=[ReplyElement {
    ReplySeq=47489  // OK. 可以通过47489这个ID查找到消息原文
  }]
}

// 转发第一次分享的卡片
Message {
  ID=54751
  Elems=[TextElement, LightAppElement]
  // 其中 LightAppElement 字段仍然完整保留
}

// 回复转发的卡片
Message {
  ID=....
  Elems=[ReplyElement {
    ReplySeq=-10785  // ????
  }]
}
```

**Comment by sam01101** [comment]
ReplySeq有什么问题？我感觉好像没什么问题

**Comment by povsister** [comment]
> 怪，需要实际测试

我这在安卓上用米忽悠的米游社app可以稳定复现这个问题，阅读任意帖子时，选择分享到QQ，然后就是如上所示
有开发者群么？我可以直接转发消息过来

**Comment by sam01101** [comment]
> 有开发者群么？我可以直接转发消息过来

192548878

**Comment by povsister** [comment]
> 192548878

群管理无响应.jpg

**Comment by sam01101** [comment]
> > 192548878
> 
> 群管理无响应.jpg

?草

**Comment by povsister** [comment]
> > 群管理无响应.jpg
> 
> ?草

早上九点那会就发了申请，到现在没动静
刚刚又重新发了次

**Comment by povsister** [comment]
@sam01101  群主鸽了？

**Comment by sam01101** [comment]
> @sam01101 群主鸽了？

这个群申请的账号经常被列入风险账号, 建议你去添加普通交流群`v`

**Comment by povsister** [comment]
> 这个群申请的账号经常被列入风险账号, 建议你去添加普通交流群`721829413`
没看懂意思，是谁被列入风险帐号？我吗

那边群人太多没法说事，群主没空的话我自己抽空看看吧

**Comment by sam01101** [comment]
> > 这个群申请的账号经常被列入风险账号, 建议你去添加普通交流群`721829413`
> 
> 没看懂意思，是谁被列入风险帐号？我吗
> 
> 那边群人太多没法说事，群主没空的话我自己抽空看看吧

是全部加这个群的, 我有个例子

**Comment by povsister** [comment]
> 是全部加这个群的, 我之前也是

我看700多号人以为是水群（

**Comment by sam01101** [comment]
> > 是全部加这个群的, 我之前也是
> 
> 我看700多号人以为是水群（

交流群确实是水群

**Comment by Mrs4s** [comment]
我晚上测试下, 可能是什么奇怪的机制

**Comment by povsister** [comment]
> 我晚上测试下, 可能是什么奇怪的机制

前两天简单看了下没细测，ReplySequence从protocolbuffer unmarshal出来是个slice，当前miraigo的实现是取了slice[0]的值。
估计可能在这有个坑啥的。

**Comment by wdvxdr1123** [comment]
可以试试最新的版本，前几天该过这部分

**Comment by povsister** [comment]
> 可以试试最新的版本，前几天该过这部分

看了下你改的部分应该是不影响这个问题的，我的场景里Bot是一直接收消息的，所以不存在SendPrivateMessage的时候message sequence id的问题。下面你改动的Parse那块，没有实质性改动只是优化了一下逻辑判定

**Comment by wdvxdr1123** [comment]
请问你说的转发是机器人的操作吗？

**Comment by povsister** [comment]
> 请问你说的转发是机器人的操作吗？

我自己的操作，机器人纯接收。
比如说我测试场景是，和机器人私聊，我分享给机器人一个链接卡片
第一次回复这个卡片的时候，repSeq是正确的
我再长按之前的消息，再次转发这个卡片给机器人，repSeq就莫名成负数了。

这个问题同样发生于：
我从群里长按转发一个链接卡片给机器人，然后回复这个转发的卡片，repSeq同样不正确。

**Comment by povsister** [comment]
can not reproduce..
怀疑腾讯当天抽风。。
