### ISSUE TITLE
可以询问下如何进行图片和表情包的区分吗

### ISSUE THREAD

**Issue by MessiahJK** [Mrs4s/MiraiGo#161]
现在想计算下图片的重复次数）表情包除外，因为表情包重复次数太多
然后看了消息体，但还是不知道怎么区分，可以询问下吗

**Comment by sam01101** [comment]
看下信息ID, 有区分得

**Comment by Mrs4s** [comment]
可以, 有专门的 `flag` , 可以考虑作为一个字段显式表示
