### ISSUE TITLE
整理下API，支持编译成C库

### ISSUE THREAD

**Issue by nnnewb** [Mrs4s/MiraiGo#167]
方便集成到各种不同语言、环境，也容易二次分发。

就是cgo要考虑的细节问题蛮多的，之前试过改 go-cqhttp ，用 JSON 当Go和C交换数据的格式，导出了 Login/Send/Recv，虽然能在 x86 下跑起来但树莓派上还会 panic。

先提个设想，看看有人感兴趣不。

**Comment by sam01101** [comment]
这个可以关了，目前C库已经有在开发了，这是没放出来
gocq成员可以参考下 https://github.com/gocq/c-cqhttp

**Comment by nnnewb** [comment]
> 这个可以关了，目前C库已经有在开发了，这是没放出来
> gocq成员可以参考下 https://github.com/gocq/c-cqhttp

1，目前啥进度？
2，大略是什么方案，完全用C重写？还是CGO导出？
3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？

关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。

最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。

**Comment by Mrs4s** [comment]
> > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> 
> 1，目前啥进度？
> 2，大略是什么方案，完全用C重写？还是CGO导出？
> 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> 
> 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> 
> 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。

实际上编译成C库会有很多问题, 比较主要的有
1.  `GO` 的数据结构并没有很好的方案直接转换成转换成 `C` 的数据结构
2.  目前的API返回用了很多 `GO` 的特性 比如元组.
3.  目前的事件实现需要传入 `GO` 的函数指针作为回调

之前其实考虑过一部分这方面的问题 当初也是考虑使用 `json` 作为传值, 但这并不怎么优雅
可能还是得等 `CGO` 更进一步优化后才会做这方面的工作

**Comment by Mrs4s** [comment]
> > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> 
> 1，目前啥进度？
> 2，大略是什么方案，完全用C重写？还是CGO导出？
> 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> 
> 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> 
> 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。

另外它是老人上人了, 不是很懂回复, 无视就好

**Comment by sam01101** [comment]
> > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> 
> 1，目前啥进度？
> 2，大略是什么方案，完全用C重写？还是CGO导出？
> 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> 
> 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> 
> 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。

1. 由于之前我只是在写着当玩具，目前的API并不完整所以Private了
2. 先不说方案，直接说思路比较容易理解
首先把 `gocq` 当库，然后再额外写一个wrapper来和C沟通
导出是 `CGo`, 但缺点是有些内存需要在自己的语言中主动释放
3. 如果是更底层的话我自己感觉就和重写一个 `gocq` 一样了，目前的方案wrapper套wrapper我是用起来爽，但底层写起真的要花很多时间写

你不喜欢我的回复我在这里可以进行道歉，我个人本身语气就有点问题，这点真的见谅。

**Comment by sam01101** [comment]
> > > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> > 
> > 
> > 1，目前啥进度？
> > 2，大略是什么方案，完全用C重写？还是CGO导出？
> > 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> > 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> > 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。
> 
> 实际上编译成C库会有很多问题, 比较主要的有
> 
> 1. `GO` 的数据结构并没有很好的方案直接转换成转换成 `C` 的数据结构
> 2. 目前的API返回用了很多 `GO` 的特性 比如元组.
> 3. 目前的事件实现需要传入 `GO` 的函数指针作为回调
> 
> 之前其实考虑过一部分这方面的问题 当初也是考虑使用 `json` 作为传值, 但这并不怎么优雅
> 可能还是得等 `CGO` 更进一步优化后才会做这方面的工作

Go数据转C架构我已经解决了
不过Array那边其实我也卡住了，因为有两个方案可以选但我不知道该用那个方案

**Comment by sam01101** [comment]
> > > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> > 
> > 
> > 1，目前啥进度？
> > 2，大略是什么方案，完全用C重写？还是CGO导出？
> > 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> > 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> > 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。
> 
> 另外它是老人上人了, 不是很懂回复, 无视就好, 那个库我都没有权限的

人上人我可不会承认，我只会承认自己语气问题
那个库我邀请你好几次了，连在群自己和你说你也不进，我也以Owner的权限在邀请你进来的

我不太懂你不进来的原因，虽然也没权得知，但请你不要拿这点说事
我主动邀请都有还几次了，Email我相信你也收到了好几封，但你没理会就是了

**Comment by nnnewb** [comment]
> > > > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > > > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> > > 
> > > 
> > > 1，目前啥进度？
> > > 2，大略是什么方案，完全用C重写？还是CGO导出？
> > > 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> > > 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> > > 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。
> > 
> > 
> > 实际上编译成C库会有很多问题, 比较主要的有
> > 
> > 1. `GO` 的数据结构并没有很好的方案直接转换成转换成 `C` 的数据结构
> > 2. 目前的API返回用了很多 `GO` 的特性 比如元组.
> > 3. 目前的事件实现需要传入 `GO` 的函数指针作为回调
> > 
> > 之前其实考虑过一部分这方面的问题 当初也是考虑使用 `json` 作为传值, 但这并不怎么优雅
> > 可能还是得等 `CGO` 更进一步优化后才会做这方面的工作
> 
> Go数据转C架构我已经解决了
> 不过Array那边其实我也卡住了，因为有两个方案可以选但我不知道该用那个方案

go 的 slice 和 map 两个内置结构想直接和 C 在 binary 级别兼容应该做不到吧，更别提 chan 了，有点想不大明白是如何实现的  go 结构转 c 结构。毕竟 go 结构里可能带这种没法兼容的东西，中间加一层序列化到其他数据交换的格式（上文所述 json），排除掉 chan 这类内置类型的话反而很好理解。

不过你说是在 gocq 上开发的话，这个包装应该是比 miraigo 更上层一些的 API 上做的吧，那主要的问题应该还是集中在 slice 。

**Comment by sam01101** [comment]
> > > > > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > > > > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> > > > 
> > > > 
> > > > 1，目前啥进度？
> > > > 2，大略是什么方案，完全用C重写？还是CGO导出？
> > > > 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> > > > 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> > > > 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。
> > > 
> > > 
> > > 实际上编译成C库会有很多问题, 比较主要的有
> > > 
> > > 1. `GO` 的数据结构并没有很好的方案直接转换成转换成 `C` 的数据结构
> > > 2. 目前的API返回用了很多 `GO` 的特性 比如元组.
> > > 3. 目前的事件实现需要传入 `GO` 的函数指针作为回调
> > > 
> > > 之前其实考虑过一部分这方面的问题 当初也是考虑使用 `json` 作为传值, 但这并不怎么优雅
> > > 可能还是得等 `CGO` 更进一步优化后才会做这方面的工作
> > 
> > 
> > Go数据转C架构我已经解决了
> > 不过Array那边其实我也卡住了，因为有两个方案可以选但我不知道该用那个方案
> 
> go 的 slice 和 map 两个内置结构想直接和 C 在 binary 级别兼容应该做不到吧，更别提 chan 了，有点想不大明白是如何实现的 go 结构转 c 结构。毕竟 go 结构里可能带这种没法兼容的东西，中间加一层序列化到其他数据交换的格式（上文所述 json），排除掉 chan 这类内置类型的话反而很好理解。
> 
> 不过你说是在 gocq 上开发的话，这个包装应该是比 miraigo 更上层一些的 API 上做的吧，那主要的问题应该还是集中在 slice 。

这样吧，我不如自己把两个Repo公开出来吧，不过我会标注“未完成”
免得有人拿来作为Production

**Comment by sam01101** [comment]
一开始想吧Go转进Python的，但没好的bridage
于是便想到了C，这就是这个Repo出现的原因

**Comment by nnnewb** [comment]
> > > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> > 
> > 
> > 1，目前啥进度？
> > 2，大略是什么方案，完全用C重写？还是CGO导出？
> > 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> > 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> > 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。
> 
> 实际上编译成C库会有很多问题, 比较主要的有
> 
> 1. `GO` 的数据结构并没有很好的方案直接转换成转换成 `C` 的数据结构
> 2. 目前的API返回用了很多 `GO` 的特性 比如元组.
> 3. 目前的事件实现需要传入 `GO` 的函数指针作为回调
> 
> 之前其实考虑过一部分这方面的问题 当初也是考虑使用 `json` 作为传值, 但这并不怎么优雅
> 可能还是得等 `CGO` 更进一步优化后才会做这方面的工作

感谢答复。

CGO 的确各方面问题很多，当初在 go-cqhttp 上折腾也是费了老大一番功夫，我个人想法其实是在 go-cqhttp ws 这套基础上（最好是 MiraiGo 这个基础上）导出一套C接口的，当时还找到一个生成 python binding 的项目 [gopy](https://github.com/go-python/gopy) 。

考虑的主要方案其实是写一个 code generator 去生成中间的 CGO 胶水，对 MiraiGO 这个项目来说其实主要是生成 client 这个包 ，甚至就 QQClient 这个结构和方法的胶水代码就好。

**Comment by sam01101** [comment]
> > > > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > > > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> > > 
> > > 
> > > 1，目前啥进度？
> > > 2，大略是什么方案，完全用C重写？还是CGO导出？
> > > 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> > > 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> > > 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。
> > 
> > 
> > 实际上编译成C库会有很多问题, 比较主要的有
> > 
> > 1. `GO` 的数据结构并没有很好的方案直接转换成转换成 `C` 的数据结构
> > 2. 目前的API返回用了很多 `GO` 的特性 比如元组.
> > 3. 目前的事件实现需要传入 `GO` 的函数指针作为回调
> > 
> > 之前其实考虑过一部分这方面的问题 当初也是考虑使用 `json` 作为传值, 但这并不怎么优雅
> > 可能还是得等 `CGO` 更进一步优化后才会做这方面的工作
> 
> 感谢答复。
> 
> CGO 的确各方面问题很多，当初在 go-cqhttp 上折腾也是费了老大一番功夫，我个人想法其实是在 go-cqhttp ws 这套基础上（最好是 MiraiGo 这个基础上）导出一套C接口的，当时还找到一个生成 python binding 的项目 [gopy](https://github.com/go-python/gopy) 。
> 
> 考虑的主要方案其实是写一个 code generator 去生成中间的 CGO 胶水，对 MiraiGO 这个项目来说其实主要是生成 client 这个包 ，甚至就 QQClient 这个结构和方法的胶水代码就好。

我这次除了 goc-cqhttp之外还公开了 py-cqhttp，一个以goc cq的python lib
进步是同步的，因为一起开发

**Comment by nnnewb** [comment]
> 一开始想吧Go转进Python的，但没好的bridage
> 于是便想到了C，这就是这个Repo出现的原因

巧了，我之前干的就是这个，把 go-cqhttp 用 JSON 当数据交换格式，硬导出了 Send/Recv ，其他代码基本保持类似 ws 协议的模式。

原本是在我fork地分支里的，不过因为和上游差别太大，而且发现还有bug没法跟进，暂时就把分支给删了。回头再提上来。

**Comment by sam01101** [comment]
> > > > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > > > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> > > 
> > > 
> > > 1，目前啥进度？
> > > 2，大略是什么方案，完全用C重写？还是CGO导出？
> > > 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> > > 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> > > 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。
> > 
> > 
> > 实际上编译成C库会有很多问题, 比较主要的有
> > 
> > 1. `GO` 的数据结构并没有很好的方案直接转换成转换成 `C` 的数据结构
> > 2. 目前的API返回用了很多 `GO` 的特性 比如元组.
> > 3. 目前的事件实现需要传入 `GO` 的函数指针作为回调
> > 
> > 之前其实考虑过一部分这方面的问题 当初也是考虑使用 `json` 作为传值, 但这并不怎么优雅
> > 可能还是得等 `CGO` 更进一步优化后才会做这方面的工作
> 
> 感谢答复。
> 
> CGO 的确各方面问题很多，当初在 go-cqhttp 上折腾也是费了老大一番功夫，我个人想法其实是在 go-cqhttp ws 这套基础上（最好是 MiraiGo 这个基础上）导出一套C接口的，当时还找到一个生成 python binding 的项目 [gopy](https://github.com/go-python/gopy) 。
> 
> 考虑的主要方案其实是写一个 code generator 去生成中间的 CGO 胶水，对 MiraiGO 这个项目来说其实主要是生成 client 这个包 ，甚至就 QQClient 这个结构和方法的胶水代码就好。

我前面也提到了，用 MiraiGo 开发根本不是问题，问题是目前没有人愿意花这么多时间去写

因为从底层写一个wrapper出来实在是浪费自己的时间，那么一开始就用gocq就好了

**Comment by sam01101** [comment]
> > 一开始想吧Go转进Python的，但没好的bridage
> > 于是便想到了C，这就是这个Repo出现的原因
> 
> 巧了，我之前干的就是这个，把 go-cqhttp 用 JSON 当数据交换格式，硬导出了 Send/Recv ，其他代码基本保持类似 ws 协议的模式。
> 
> 原本是在我fork地分支里的，不过因为和上游差别太大，而且发现还有bug没法跟进，暂时就把分支给删了。回头再提上来。

这个有缺点的，转换格式会浪费一点性能，所以API对API入手会比较好
虽然维护会哭死

**Comment by nnnewb** [comment]
> > > > > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > > > > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> > > > 
> > > > 
> > > > 1，目前啥进度？
> > > > 2，大略是什么方案，完全用C重写？还是CGO导出？
> > > > 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> > > > 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> > > > 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。
> > > 
> > > 
> > > 实际上编译成C库会有很多问题, 比较主要的有
> > > 
> > > 1. `GO` 的数据结构并没有很好的方案直接转换成转换成 `C` 的数据结构
> > > 2. 目前的API返回用了很多 `GO` 的特性 比如元组.
> > > 3. 目前的事件实现需要传入 `GO` 的函数指针作为回调
> > > 
> > > 之前其实考虑过一部分这方面的问题 当初也是考虑使用 `json` 作为传值, 但这并不怎么优雅
> > > 可能还是得等 `CGO` 更进一步优化后才会做这方面的工作
> > 
> > 
> > 感谢答复。
> > CGO 的确各方面问题很多，当初在 go-cqhttp 上折腾也是费了老大一番功夫，我个人想法其实是在 go-cqhttp ws 这套基础上（最好是 MiraiGo 这个基础上）导出一套C接口的，当时还找到一个生成 python binding 的项目 [gopy](https://github.com/go-python/gopy) 。
> > 考虑的主要方案其实是写一个 code generator 去生成中间的 CGO 胶水，对 MiraiGO 这个项目来说其实主要是生成 client 这个包 ，甚至就 QQClient 这个结构和方法的胶水代码就好。
> 
> 我前面也提到了，用 MiraiGo 开发根本不是问题，问题是目前没有人愿意花这么多时间去写
> 
> 因为从底层写一个wrapper出来实在是浪费自己的时间，那么一开始就用gocq就好了

gocq 最大的问题是接口，原本的 cqhttp 协议老实说我觉得定的不是很好，但现在即使有 onebot ，为了兼容之类的说法，也很难做出什么大的改动了。

**Comment by sam01101** [comment]
以gocq作为wrapper的一个优点是你可以自定义API，如果需要一些object可以写个API将其转成C然后读取

**Comment by sam01101** [comment]
> > > > > > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > > > > > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> > > > > 
> > > > > 
> > > > > 1，目前啥进度？
> > > > > 2，大略是什么方案，完全用C重写？还是CGO导出？
> > > > > 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> > > > > 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> > > > > 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。
> > > > 
> > > > 
> > > > 实际上编译成C库会有很多问题, 比较主要的有
> > > > 
> > > > 1. `GO` 的数据结构并没有很好的方案直接转换成转换成 `C` 的数据结构
> > > > 2. 目前的API返回用了很多 `GO` 的特性 比如元组.
> > > > 3. 目前的事件实现需要传入 `GO` 的函数指针作为回调
> > > > 
> > > > 之前其实考虑过一部分这方面的问题 当初也是考虑使用 `json` 作为传值, 但这并不怎么优雅
> > > > 可能还是得等 `CGO` 更进一步优化后才会做这方面的工作
> > > 
> > > 
> > > 感谢答复。
> > > CGO 的确各方面问题很多，当初在 go-cqhttp 上折腾也是费了老大一番功夫，我个人想法其实是在 go-cqhttp ws 这套基础上（最好是 MiraiGo 这个基础上）导出一套C接口的，当时还找到一个生成 python binding 的项目 [gopy](https://github.com/go-python/gopy) 。
> > > 考虑的主要方案其实是写一个 code generator 去生成中间的 CGO 胶水，对 MiraiGO 这个项目来说其实主要是生成 client 这个包 ，甚至就 QQClient 这个结构和方法的胶水代码就好。
> > 
> > 
> > 我前面也提到了，用 MiraiGo 开发根本不是问题，问题是目前没有人愿意花这么多时间去写
> > 因为从底层写一个wrapper出来实在是浪费自己的时间，那么一开始就用gocq就好了
> 
> gocq 最大的问题是接口，原本的 cqhttp 协议老实说我觉得定的不是很好，但现在即使有 onebot ，为了兼容之类的说法，也很难做出什么大的改动了。

大改动可以的，可惜没时间，我可能要过两年才可以有比较长的时间去慢慢写，所以我目前采取的方式是闲置需要大量时间的东西

**Comment by nnnewb** [comment]
> > > 一开始想吧Go转进Python的，但没好的bridage
> > > 于是便想到了C，这就是这个Repo出现的原因
> > 
> > 
> > 巧了，我之前干的就是这个，把 go-cqhttp 用 JSON 当数据交换格式，硬导出了 Send/Recv ，其他代码基本保持类似 ws 协议的模式。
> > 原本是在我fork地分支里的，不过因为和上游差别太大，而且发现还有bug没法跟进，暂时就把分支给删了。回头再提上来。
> 
> 这个有缺点的，转换格式会浪费一点性能，所以API对API入手会比较好
> 虽然维护会哭死

性能还真不是我关注的重点。。毕竟光是把网络io去掉，中间又没添加别的间接层，性能再烂也不会比gocq差了。

**Comment by Mrs4s** [comment]
> > > > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > > > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> > > 
> > > 
> > > 1，目前啥进度？
> > > 2，大略是什么方案，完全用C重写？还是CGO导出？
> > > 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> > > 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> > > 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。
> > 
> > 
> > 另外它是老人上人了, 不是很懂回复, 无视就好, 那个库我都没有权限的
> 
> 人上人我可不会承认，我只会承认自己语气问题
> 那个库我邀请你好几次了，连在群自己和你说你也不进，我也以Owner的权限在邀请你进来的
> 
> 我不太懂你不进来的原因，虽然也没权得知，但请你不要拿这点说事
> 我主动邀请都有还几次了，Email我相信你也收到了好几封，但你没理会就是了

这个不是你承不承认的问题, 很明显的是, 如果一个 `issue` 或者问题涉及到任何相对与你的信息不对称的话, 你的回复就会不由自主的带上优越感甚至开始嘲讽, 社区项目最忌讳的就是优越感, 并不是你参与了某某项目, 做出了某些贡献就能高人一等的. 而这个问题我在各个issue/群里已经不止一次针对这个问题提醒过你了, 你也确实因为这种问题(态度)引发了一些根本不必要的争论. 

最近我比较忙没有太多精力维护项目回复issue, 而你确实在帮助建设社区, 这是值得感谢的, 但也希望能本着友好的态度解决问题, 帮助小白, 不要一上来就说教般的火药味十足.

**Comment by sam01101** [comment]
> > > > 一开始想吧Go转进Python的，但没好的bridage
> > > > 于是便想到了C，这就是这个Repo出现的原因
> > > 
> > > 
> > > 巧了，我之前干的就是这个，把 go-cqhttp 用 JSON 当数据交换格式，硬导出了 Send/Recv ，其他代码基本保持类似 ws 协议的模式。
> > > 原本是在我fork地分支里的，不过因为和上游差别太大，而且发现还有bug没法跟进，暂时就把分支给删了。回头再提上来。
> > 
> > 
> > 这个有缺点的，转换格式会浪费一点性能，所以API对API入手会比较好
> > 虽然维护会哭死
> 
> 性能还真不是我关注的重点。。毕竟光是把网络io去掉，中间又没添加别的间接层，性能再烂也不会比gocq差了。

你懂我的哭了吧，这就是我为什么需要特意开发这个wrapper的原因

**Comment by sam01101** [comment]
> > > > > 这个可以关了，目前C库已经有在开发了，这是没放出来
> > > > > gocq成员可以参考下 https://github.com/gocq/c-cqhttp
> > > > 
> > > > 
> > > > 1，目前啥进度？
> > > > 2，大略是什么方案，完全用C重写？还是CGO导出？
> > > > 3，目标是一个和go-cqhttp类似的cqhttp实现，还是一个更底层一些的，提供基本QQ协议实现的库？
> > > > 关issue没有问题。但我不喜欢你的回复，你的回复没有解决也没有说明正在解决什么问题，以什么方式解决，如何参与（或者是否欢迎参与）。没有任何有效信息。
> > > > 最终给人的感觉就是：“我在做，你们别吵”。这种回应方式，只会让人觉得傲慢和不尊重。
> > > 
> > > 
> > > 另外它是老人上人了, 不是很懂回复, 无视就好, 那个库我都没有权限的
> > 
> > 
> > 人上人我可不会承认，我只会承认自己语气问题
> > 那个库我邀请你好几次了，连在群自己和你说你也不进，我也以Owner的权限在邀请你进来的
> > 我不太懂你不进来的原因，虽然也没权得知，但请你不要拿这点说事
> > 我主动邀请都有还几次了，Email我相信你也收到了好几封，但你没理会就是了
> 
> 这个不是你承不承认的问题, 很明显的是, 如果一个 `issue` 或者问题涉及到任何相对与你的信息不对称的话, 你的回复就会不由自主的带上优越感甚至开始嘲讽, 社区项目最忌讳的就是优越感, 并不是你参与了某某项目, 做出了某些贡献就能高人一等的. 而这个问题我在各个issue/群里已经不止一次针对这个问题提醒过你了, 你也确实因为这种问题(态度)引发了一些根本不必要的争论.
> 
> 最近我比较忙没有太多精力维护项目回复issue, 而你确实在帮助建设社区, 这是值得感谢的, 但也希望能本着友好的态度解决问题, 帮助小白, 不要一上来就说教般的火药味十足.

优越感早就被很多因素刷下来了，我很久就没有以前那种脾气了
你也知道我以前可是怼着人的，我现在的态度是真的放下来了
如果有人真的不满意我的答复，他们完全可以对我提出意见，甚至骂我
我也肯定会道歉，而不是像以前那样引战
这只会让大家难受

我不认为我的嘲讽是对自己优越感而产生出来的，这个世界上一堆人比我还努力，那我干嘛要把自己当成人上人呢？

**Comment by nnnewb** [comment]
> 大改动可以的，可惜没时间，我可能要过两年才可以有比较长的时间去慢慢写，所以我目前采取的方式是闲置需要大量时间的东西

稍提醒下，这个**大改动可以**显然是口嗨了，gocq这个项目不是你一个人的项目，onebot也不是你的一言堂，而现在这个 issue讨论的主题也不是你的 ccq 项目。

> 你懂我的哭了吧，这就是我为什么需要特意开发这个wrapper的原因

emm，性能讲道理，mirai又不是什么计算密集或者内存密集型的应用，也不用考虑什么c100k之类的问题....

好吧，不做评论。

**Comment by sam01101** [comment]
> > 大改动可以的，可惜没时间，我可能要过两年才可以有比较长的时间去慢慢写，所以我目前采取的方式是闲置需要大量时间的东西
> 
> 稍提醒下，这个**大改动可以**显然是口嗨了，gocq这个项目不是你一个人的项目，onebot也不是你的一言堂，而现在这个 issue讨论的主题也不是你的 ccq 项目。
> 
> > 你懂我的哭了吧，这就是我为什么需要特意开发这个wrapper的原因
> 
> emm，性能讲道理，mirai又不是什么计算密集或者内存密集型的应用，也不用考虑什么c100k之类的问题....
> 
> 好吧，不做评论。

这个闲置是指我所开的各种issue和PR，这个项目不可能只有我一个人而成的，这点是我表达不清晰而造成的

mirai那个是以java的KVM开发，但我很久没去留意了所以不清楚

**Comment by sam01101** [comment]
还有，我不是指onebot那个协议的重构，那也是我和另外一个朋友合作的一个项目，目的是写出一个能够对对象语言友好的协议
所以，我真TM讨厌中文表达就是这个原因，但无奈用要表达出自己意思就必须用语言，什么时候才可以不用透过语言就可以表达自己的意思给对方啊
