### ISSUE TITLE
SendPrivateMessage无法发送字数较多的消息吗？

### ISSUE THREAD

**Issue by orzogc** [Mrs4s/MiraiGo#17]
尝试用`SendPrivateMessage`发送几百字的消息，目标QQ完全没有收到消息，返回的`*message.PrivateMessage`应该是没有问题的。

原版的Mirai没有用过，但酷Q可以发送字数较多的消息。

**Comment by Mrs4s** [comment]
暂不支持私聊的长消息发送

**Comment by Mrs4s** [comment]
私聊长消息已支持.

**Comment by orzogc** [comment]
谢谢
