### ISSUE TITLE
统一版本号，可以改成常量

### ISSUE THREAD

**Issue by lz1998** [Mrs4s/MiraiGo#172]
在代码中搜索正则表达式`\d\.\d\.\d`，发现有很多不同版本QQ
- 8.4.18
- 8.2.7
- 8.4.5
- 8.5.0
- 8.2.0

**Comment by LXY1226** [comment]
草 还有这种事?

**Comment by lz1998** [comment]
> 草 还有这种事?

搜一下还挺多的，比如 https://github.com/Mrs4s/MiraiGo/blob/master/client/multimsg.go#L32
