### ISSUE TITLE
可以讲一下更新后的ImageElement是怎么用的吗

### ISSUE THREAD

**Issue by Sora233** [Mrs4s/MiraiGo#178]
之前的ImageElement替换成哪个呢？
```
	Flash    bool
	EffectID int32
```
这两个具体怎么用呢

**Comment by wdvxdr1123** [comment]
按照消息类型换成 GroupImageElement 和 FriendImageElement 就行
Flash是闪照
effectId是秀图（不推荐使用），可以参考:
https://github.com/Mrs4s/go-cqhttp/blob/master/docs/cqhttp.md#cqcode-1

btw,神秘号码:https://github.com/Mrs4s/go-cqhttp/blob/master/main.go#L157

**Comment by Sora233** [comment]
感谢回复
