### ISSUE TITLE
GroupInfo 中的 Uin 和 Code 有何区别？

### ISSUE THREAD

**Issue by asjdf** [Mrs4s/MiraiGo#181]
![image](https://user-images.githubusercontent.com/22193008/130109726-978807d7-e858-48bd-82f1-c8035f193154.png)
是在什么情况会有不同吗？还是历史遗留问题？

**Comment by sam01101** [comment]
先有 Code，後有 Uin
看Utils

**Comment by Mrs4s** [comment]
`Code` 为QQ客户端显示的"群号", 新群 `Uin` 和 `Code` 基本一样, 老群可能会有不一样的情况.
大部分API都接收 `Code` 作为参数, 但是也有一些使用 `Uin` 的API.
QQ客户端内部也有将`Code` 赋值到名为 `GroupUin` 变量来使用的情况.
可以推测 `Uin` 应该是上古时代的群号, 后来可能为了靓号之类的业务造了一个 "显示群号" 之类的东西. 然后逐渐变成主流了.
总之这多半是一个来自QQ的历史遗留问题
