### ISSUE TITLE
请问有没有可能支持聊天成员的头像地址获取？

### ISSUE THREAD

**Issue by LainNetWork** [Mrs4s/MiraiGo#182]
之前使用Mirai-Core的时候，可以获取对话或者At对象的Member对象，里面可以获取到对方的avatarUrl，请问MiraiGO以及go-cqhttp有可能支持这一特性吗？

```java
  NormalMember normalMember = subject.get(at.getTarget());
  if(normalMember == null){
      return;
  }
  String avatarUrl = normalMember.getAvatarUrl();
```

**Comment by wdvxdr1123** [comment]
请使用  https://q1.qlogo.cn/g?b=qq&nk=QQ号&s=640

**Comment by LainNetWork** [comment]
> 请使用 [https://q1.qlogo.cn/g?b=qq&nk=QQ号&s=640](https://q1.qlogo.cn/g?b=qq&nk=QQ%E5%8F%B7&s=640)

还有这种方式！。。感谢解答！
