### ISSUE TITLE
Can I Send a File?

### ISSUE THREAD

**Issue by ScSofts** [Mrs4s/MiraiGo#19]
Hello,I would link to create a software auto publisher,but I cannot find the API to send a file.
Thank you for help.

**Comment by ScSofts** [comment]
OK Thanks

**Comment by dzcpy** [comment]
Does Mirai support sending files?

**Comment by sam01101** [comment]
Update: Group file uploading is being support soon.
WIP: https://github.com/Mrs4s/MiraiGo/commit/c6cb5c7fe2f900375f1bbad717b18f24b230f84e
(Not finished, I'll update this when it's support)

**Comment by Mrs4s** [comment]
group file uploading is supported now.
