### ISSUE TITLE
一直在报错

### ISSUE THREAD

**Issue by XM2510136957** [Mrs4s/MiraiGo#195]
[2021-11-10 14:01:11] [ERROR]: MiraiGo -> panic on decoder MultiMsg.ApplyDown : runtime error: invalid memory address or nil pointer dereference
goroutine 586482 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20211011130217-a3eacd706b29/client/network.go:223 +0x5d
panic({0xbcdd60, 0x198d0f0})
	runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/utils.HttpGetBytes.func1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20211011130217-a3eacd706b29/utils/http.go:23 +0x1c
github.com/Mrs4s/MiraiGo/utils.HttpGetBytes({0xc001c27500, 0x4}, {0x0, 0x2})
	github.com/Mrs4s/MiraiGo@v0.0.0-20211011130217-a3eacd706b29/utils/http.go:25 +0xb4
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc001bfab40, 0x226, {0xc001bfab40, 0x226, 0x226})
	github.com/Mrs4s/MiraiGo@v0.0.0-20211011130217-a3eacd706b29/client/multimsg.go:103 +0x1bc
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0006959f0)
	github.com/Mrs4s/MiraiGo@v0.0.0-20211011130217-a3eacd706b29/client/network.go:233 +0x1cb
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20211011130217-a3eacd706b29/client/network.go:220 +0x525

**Comment by Mrs4s** [comment]
目测tx云服务器，dns问题
可以调用 ConnectionQualityTest 函数测试下网络
