### ISSUE TITLE
[bug?] guild reaction 无法获取 operatorId 与 emojiId，即便是自己的消息收到表情贴

### ISSUE THREAD

**Issue by Bluefissure** [Mrs4s/MiraiGo#204]
[尝试去掉了不parse自己的消息](https://github.com/Bluefissure/MiraiGo/commit/fe987d351b538ec88e7212ae0ab8d45663f7ce9f)，发现还是无法获取 `operatorId` 和 `emojiId`。
或者是我的理解出错，比如接收到 tips 会被独立成另外的一个事件？

**Comment by Bluefissure** [comment]
找到问题了：如果有多个链接，只会有其中的一个进行等待 `tips` 事件，其他的链接由于收不到事件便无法获取 `operatorId`。

另外 `emojiId` 在定义中存在但是似乎并没有给其赋值。

**Comment by Bluefissure** [comment]
Upd: 似乎只有一个链接也无法稳定收到 `tips` 事件，莫非 `tips` 和 `reaction` 事件并不是先后发送的？

**Comment by Mrs4s** [comment]
> Upd: 似乎只有一个链接也无法稳定收到 `tips` 事件，莫非 `tips` 和 `reaction` 事件并不是先后发送的？

可能需要更多测试, 理论上TX应该是不想让你获取到这个的 `operatorId`

**Comment by Bluefissure** [comment]
> > Upd: 似乎只有一个链接也无法稳定收到 `tips` 事件，莫非 `tips` 和 `reaction` 事件并不是先后发送的？
> 
> 可能需要更多测试, 理论上TX应该是不想让你获取到这个的 `operatorId`

的确 `tips` 事件是独立于 `reaction` 事件的，我把它独立出来了一个新的事件 
https://github.com/Bluefissure/MiraiGo/tree/guild-message-reaction

同时去掉了 `includeUin`，这个字段似乎在这个消息的 CtrlHead 中是 `bytes`。

有个关于Contribution的问题，proto文件转换成 *.pb.go 的 `protoc-gen-golite` 是哪个工具？我似乎只能找到 `protoc-gen-go`，于是只好手动修改了 pb.go。

BTW，开发群能不能同意一下入群申请 ORZ。
