### ISSUE TITLE
[bug？]index out of range [0] with length 0

### ISSUE THREAD

**Issue by icarus-ai** [Mrs4s/MiraiGo#209]
[使用 commit e043181fc19dd33ee1f490f4ff818fae141d7835 NewClient 时越界？](https://github.com/Mrs4s/MiraiGo/commit/e043181fc19dd33ee1f490f4ff818fae141d7835)

[commit 96fd4d32e7ef415c3875551c46f8d254f81973e9 可以正常登录](https://github.com/Mrs4s/MiraiGo/commit/96fd4d32e7ef415c3875551c46f8d254f81973e9)

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).peakHead(...)
	/home/pkg/github.com/Mrs4s/MiraiGo/binary/jce/reader.go:31
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).skipToTag(0x104bdd0, 0x0)
	/home/pkg/github.com/Mrs4s/MiraiGo/binary/jce/reader.go:150 +0x16c
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).ReadMapStrByte(0x104bdd0, 0x0)
	/home/pkg/github.com/Mrs4s/MiraiGo/binary/jce/reader.go:409 +0x24
github.com/Mrs4s/MiraiGo/binary/jce.(*RequestDataVersion3).ReadFrom(...)
	/home/pkg/github.com/Mrs4s/MiraiGo/binary/jce/structs.go:573
github.com/Mrs4s/MiraiGo/client.getSSOAddress()
	/home/pkg/github.com/Mrs4s/MiraiGo/client/global.go:477 +0x6e8
github.com/Mrs4s/MiraiGo/client.NewClientMd5(0x5d85f0a0, {0x11, 0x3c, 0xda, 0xd, 0xde, 0x71, 0x79, 0x86, 0x6d, ...})
	/home/pkg/github.com/Mrs4s/MiraiGo/client/client.go:219 +0x3b8
github.com/Mrs4s/MiraiGo/client.NewClient(0x5d85f0a0, {0x101ffa0, 0x8})
	/home/pkg/github.com/Mrs4s/MiraiGo/client/client.go:187 +0x94
bot/core/login.InitClient()
	/home/bot/core/login/login.go:34 +0x1d8
main.main()
	/home/bot/main.go:39 +0x320

**Comment by wdvxdr1123** [comment]
cc @fumiama

**Comment by fumiama** [comment]
emmmm

**Comment by Mrs4s** [comment]
emmmmm

**Comment by icarus-ai** [comment]
[能登陆了](https://github.com/Mrs4s/MiraiGo/commit/d094d0483da8743c41514a203e6d4fc2e993e325)
