### ISSUE TITLE
onprivatemessage未调用函数

### ISSUE THREAD

**Issue by siteoj** [Mrs4s/MiraiGo#21]
QQ.client.onprivatemessage(func)
在A向bot发送信息后func未被调用

**Comment by orzogc** [comment]
调用了吧，在`dispatchFriendMessage`那里

**Comment by Mrs4s** [comment]
请提供更多信息

**Comment by siteoj** [comment]
> 
> 
> 调用了吧，在`dispatchFriendMessage`那里

能给个联系方式吗？帮我看看？

**Comment by siteoj** [comment]
> 
> 
> 请提供更多信息

![图片](https://user-images.githubusercontent.com/61609756/90330737-c9882580-dfe1-11ea-9b81-8c1590c271f1.png)

**Comment by Mrs4s** [comment]
用错了,  `OnPrivateMessage` 只需要调用一次, 不熟悉Go的话建议使用 [go-cqhttp](https://github.com/Mrs4s/go-cqhttp)搭配其他语言开发
