### ISSUE TITLE
代码报错，无法编译，

### ISSUE THREAD

**Issue by licowang88** [Mrs4s/MiraiGo#212]
tea.go 这个文件里的一个定义，好像不完整，如下：

// randuint32 returns a lock free uint32 value.
//go:linkname randuint32 runtime.fastrand
func randuint32() uint32

randuint32() 是个函数，但好像没有函数体。

**Comment by Mrs4s** [comment]
这个是将 `runtime.fastrand` 函数的函数体链接到这里, 是正常语法

**Comment by Ink-33** [comment]
您好，这里使用了`go:linkname`，烦请您了解一下相关用法，感谢

**Comment by licowang88** [comment]
嗯，刚尝试编译过了。不好意思，之前没有了解过相关用法。非常感谢二位的解答。
