### ISSUE TITLE
请问能给一下发送网络和本地图片的例程吗？

### ISSUE THREAD

**Issue by siteoj** [Mrs4s/MiraiGo#24]
如题，谢谢

**Comment by Mrs4s** [comment]
请参考 [这里](https://github.com/Mrs4s/go-cqhttp/blob/322b70c6b5c70c6d4fec7f53f9e13407f09904ac/coolq/cqcode.go#L262-L360)
和 [这里](https://github.com/Mrs4s/go-cqhttp/blob/322b70c6b5c70c6d4fec7f53f9e13407f09904ac/coolq/bot.go#L110-L119)

**Comment by dreamer2q** [comment]
> https://github.com/Mrs4s/go-cqhttp/blob/322b70c6b5c70c6d4fec7f53f9e13407f09904ac/coolq/bot.go#L110-L119

@Mrs4s  请问一下，为何 111、112 行调用了两次 `UploadGroupImage` 呢？

**Comment by sam01101** [comment]
> > https://github.com/Mrs4s/go-cqhttp/blob/322b70c6b5c70c6d4fec7f53f9e13407f09904ac/coolq/bot.go#L110-L119
> 
> @Mrs4s 请问一下，为何 111、112 行调用了两次 `UploadGroupImage` 呢？


114514草
是不是什麼遺留的測試代碼

**Comment by dreamer2q** [comment]
没事了，原来这些是旧的代码。
