### ISSUE TITLE
【问题】get msg error 出现 104 代码错误是什么意思 (或有无群消息获取错误代码的对应文档)

### ISSUE THREAD

**Issue by eric2788** [Mrs4s/MiraiGo#244]
机器人调用 `GetGroupMessages` 时有时候会出现 104 代码错误，一开始初步推断为 机器人未进群前的消息导致获取不了，后来实验之后又发现不太对，不知道有无一些群消息获取错误代码的对应文档让我参考一下？

**Comment by fy0** [comment]
也遇到了，但是是发消息时候？
