### ISSUE TITLE
[bug?] tcpping

### ISSUE THREAD

**Issue by icarus-ai** [Mrs4s/MiraiGo#245]
r := utils.RunTCPPingLoop("192.168.1.100:80", 4) // 这个ip上没有任何服务
	fmt.Printf("send: %v, loss: %v, avg: %v\n",
		r.PacketsSent,
		r.PacketsLoss,
		r.AvgTimeMill,
	)
打印: send4，loss0，avg1026
只把net.DialTimeout错误里的超时当成丢包，是否合理?
dial tcp 192.168.1.100:80: connect: no route to host

腾讯ubuntu服务器上测试，ping一个不存在的地址100丢包率
@fumiama

**Comment by Mrs4s** [comment]
我认为是合理的. 毕竟系统自带的 `ping` 工具如果请求一个不存在的地址也会返回100%丢包
![image](https://user-images.githubusercontent.com/12137562/150097395-c505e06d-26ab-462c-aaa3-50b89dd3ce18.png)

**Comment by icarus-ai** [comment]
![Uploading QQ图片_20220119_165845.jpg…]()

**Comment by icarus-ai** [comment]
![QQ图片_20220119_165845](https://user-images.githubusercontent.com/82353054/150098231-7fc36f2f-2701-4930-bbbc-5f08e2c273b4.jpg)

**Comment by icarus-ai** [comment]
> 我认为是合理的。系统自带的`ping`工具如果请求一个不存在的地址也会返回100%丢包 ![图片](https://user-images.githubusercontent.com/12137562/150097395-c505e06d-26ab-462c-aaa3-50b89dd3ce18.png)

但是linux上是100%
![QQ图片_20220119_165845](https://user-images.githubusercontent.com/82353054/150098231-7fc36f2f-2701-4930-bbbc-5f08e2c273b4.jpg)

**Comment by icarus-ai** [comment]
> 我认为是合理的。系统自带的`ping`工具如果请求一个不存在的地址也会返回100%丢包 ![图片](https://user-images.githubusercontent.com/12137562/150097395-c505e06d-26ab-462c-aaa3-50b89dd3ce18.png)

但是fumiama的那个tcping ping 127.0.0.1和不存在的ip loss都是0 合理?

**Comment by icarus-ai** [comment]
> 我认为是合理的。系统自带的`ping`工具如果请求一个不存在的地址也会返回100%丢包 ![图片](https://user-images.githubusercontent.com/12137562/150097395-c505e06d-26ab-462c-aaa3-50b89dd3ce18.png)

但是fumiama的那个tcping ping 127.0.0.1和不存在的ip loss都是0 合理?

**Comment by Mrs4s** [comment]
确实可能需要调整一下
