### ISSUE TITLE
OnDisconnected 一启动就会马上触发

### ISSUE THREAD

**Issue by Sora233** [Mrs4s/MiraiGo#246]
25c67a3ee1c1 不会发生
3b461554b747 会发生

**Comment by wdvxdr1123** [comment]
无法复现

**Comment by Sora233** [comment]
有点不兼容的感觉，同样的配置下：
- 25c67a3 可以直接登陆， 而 3b46155 会显示需要滑条验证码
- 当使用 25c67a3 登陆后保存token结束bot，换成 3b46155 使用token登陆，会显示`你的帐号于XX:XX在另一台iPad平板登录。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。`
