### ISSUE TITLE
获取SSO服务器列表时请求体的JCETag 14已经被移除

### ISSUE THREAD

**Issue by xtexChooser** [Mrs4s/MiraiGo#250]
本地QQ版本V8.8.68.7265，
写映射表时发现，在类`com/tencent/msf/service/protocol/serverconfig/d`(`SSOServerListRequest`)的方法`writeTo`(`write`)中已经找不到对14字段的写入，但是在[client/global.go#L128](https://github.com/Mrs4s/MiraiGo/blob/master/client/global.go#L128)中仍然向14字段写入了1字节
![image](https://user-images.githubusercontent.com/46394906/152634213-16ad36fc-7ba0-4f12-835a-bd699f516c7e.png)

**Comment by qianjunakasumi** [comment]
谢谢你的反馈，如有可能请直接 PR

**Comment by xtexChooser** [comment]
> 谢谢你的反馈，如有可能请直接 PR

不确定 & 不会Go（虽然只要删代码，万一出了什么事

**Comment by qianjunakasumi** [comment]
删除字段前

```
=== RUN   Test_getSSOAddress
109.244.153.11:8080
36.155.201.42:14000
120.232.18.27:8080
36.155.248.239:80
120.232.130.74:14000
39.156.126.162:443
36.155.229.203:80
120.232.65.165:80
39.156.125.100:80
39.156.125.79:80
--- PASS: Test_getSSOAddress (0.34s)
PASS
```

删除字段后

```
=== RUN   Test_getSSOAddress
36.155.249.120:14000
120.232.18.126:8080
36.155.229.123:8080
120.232.67.156:80
111.30.181.215:14000
36.155.249.17:443
120.232.18.27:80
111.30.178.75:80
39.156.125.20:80
--- PASS: Test_getSSOAddress (0.34s)
PASS
```

**Comment by qianjunakasumi** [comment]
比较两者，除了少一个服务器外似乎无区别
