### ISSUE TITLE
如下

### ISSUE THREAD

**Issue by siteoj** [Mrs4s/MiraiGo#26]
![图片](https://user-images.githubusercontent.com/61609756/90769075-3c670880-e322-11ea-891a-0ce55eb82ebc.png)
![图片](https://user-images.githubusercontent.com/61609756/90769091-425ce980-e322-11ea-8981-3562dc272b2e.png)
读入图片是成功的，可以转为base64编码并且解码为图片成功。
麻烦看看好吗？

**Comment by Mrs4s** [comment]
本地文件需要上传. 建议使用go-cqhttp

**Comment by siteoj** [comment]
好吧，希望作者能够完善这个的文档，cqhttp的那些sdk，我全都会报错
