### ISSUE TITLE
不停的报错

### ISSUE THREAD

**Issue by ZakiuC** [Mrs4s/MiraiGo#261]
![image](https://user-images.githubusercontent.com/74860740/158912397-a13a16bd-29f9-4398-b200-21c9bc72d6c7.png)

**Comment by ZakiuC** [comment]
![image](https://user-images.githubusercontent.com/74860740/158913641-4a3870ef-00af-4ac2-875a-d120c66ab41b.png)

**Comment by ishkong** [comment]
你说的我都遇到了，给你提供些临时解决方案
图一：换服务器，主要是换网络，或者无视直接重启gocq
图二：换号，非要用这个号就在报错后30-90秒内再试一次，有概率能用
