### ISSUE TITLE
msg.proto 里的 _400Url 这个属性是必须要在proto文件里写出来吗

### ISSUE THREAD

**Issue by wulunshijian** [Mrs4s/MiraiGo#292]
![image](https://user-images.githubusercontent.com/46415928/184139299-b6f45011-5c03-46e4-aa47-508174ea7f4f.png)
这个_400Url 在其他开发语言钟疑似无法protoc 生成对应语言的变量。
![image](https://user-images.githubusercontent.com/46415928/184139507-625eeb92-ba0a-4a13-91fc-47c85d7a47d0.png)
这是c#版本的，通过google.protobuf  protoc --csharp_out 生成的属性命名是有误，导致无法编译成功。是否可以将这个变量排除proto文件外

**Comment by xtexChooser** [comment]
改个名不就好了，ProtoBuf是TTLV的，输出结果只和number有关，那个名字是给代码看的，加这个`_`只是为了不以数字开头，随便改成别的就好。

**Comment by wulunshijian** [comment]
> 改个名不就好了，ProtoBuf是TTLV的，输出结果只和number有关，那个名字是给代码看的，加这个`_`只是为了不以数字开头，随便改成别的就好。

好的，谢谢帮忙解答疑问
