### ISSUE TITLE
ipad协议可能被腾讯暗改

### ISSUE THREAD

**Issue by icarus-ai** [Mrs4s/MiraiGo#298]
使用ipad协议，设备锁开启，[d3b8c5](https://github.com/Mrs4s/MiraiGo/commit/d3b8c5f700af945af09d90febdccc340841d37ac)登录提示版本过低(密码正确)，[18c0d1，update android phone protocol to v8.8.38](https://github.com/Mrs4s/MiraiGo/commit/18c0d17be53d15cb2bcf2b5d88154f71eaa9eb5c) 正常登录，[ddf1e5，update ipad protocol to v8.8.35](https://github.com/Mrs4s/MiraiGo/commit/ddf1e5e3711c61302024310f1052f9dfa0596348) 的versionInfo被腾讯扬了?

**Comment by weilinfox** [comment]
我这样改 IPad 协议就可以登陆了说（从 [OICQ](https://github.com/takayama-lily/oicq/blob/main/lib/core/device.ts#L146) 抄的）。

```
AppId:           537067382,
SubAppId:        537067382,
SortVersionName: "5.8.9",
// 或者
SortVersionName: "5.9.3",
```

但是不知道为啥我就是收不到戳一戳这些 notify 消息。
