### ISSUE TITLE
如何上传语音(非tts)

### ISSUE THREAD

**Issue by eric2788** [Mrs4s/MiraiGo#301]
我注意到 miraigo 有一个 api 叫  `UploadGroupPtt` 或 `UploadPrivatePtt` 这两个方法在上传tts语音的时候都没有问题。但是如果我想上传 mp3 或者 wav 的音讯档案，就会变成可以发送语音但是播放会没有声音的状态。

查了查原始码，好像是需要转换成 .amr 才可以使用上传吗？还是有更简单的方法可以直接发送 mp3 或 wav 的语音呢？谢谢

还是已经在新版本 UploadVoice 下已经可以上传了？

**Comment by eric2788** [comment]
測試了一下 `UploadVoice` 上傳 mp3 或者 wav 還是會變成可以播放但沒有聲音

**Comment by wdvxdr1123** [comment]
FYI:
https://github.com/Mrs4s/go-cqhttp/blob/master/modules/silk/codec.go

**Comment by eric2788** [comment]
> FYI: [https://github.com/Mrs4s/go-cqhttp/blob/master/modules/silk/codec.go](https://github.com/Mrs4s/go-cqhttp/blob/master/modules/silk/codec.go?rgh-link-date=2022-11-05T08%3A24%3A13Z)

我寫了一個類似的，也是用你的api，但好像播放沒有聲音，又或者是雜音
https://github.com/eric2788/MiraiValBot/blob/master/aivoice/aivoice.go

**Comment by eric2788** [comment]
用的wav是原神tts: https://github.com/eric2788/MiraiValBot/blob/ccac4dcc6c2d2102b838e6e7cb29742baa04d06a/aivoice/genshin_voice.go#L101

**Comment by wdvxdr1123** [comment]
请使用 ​github.com/wdvxdr1123/go-silk​ ​v0.0.0-20210316130616-d47b553def60

master上好像被我更新炸了，一直没时间改

**Comment by eric2788** [comment]
> github.com/wdvxdr1123/go-silk​ ​v0.0.0-20210316130616-d47b553def60

好的，我試試看

**Comment by eric2788** [comment]
有點奇怪，改版之後是可以播放，但是嘗試播放一些mp3和wav上傳語音之後就沒聲音，再播放回silk還是沒聲音，但是手機qq的話好像mp3/wav/silk都可以播放

**Comment by wdvxdr1123** [comment]
@eric2788  pc客户端的bug， 播放一次错误语音后，无法播放其他语音，需要重启一次客户端

**Comment by eric2788** [comment]
> @eric2788  pc客户端的bug， 播放一次错误语音后，无法播放其他语音，需要重启一次客户端

所以mp3和wav在pc客戶端是錯誤的（沒聲音
但手機端卻是正常的？

**Comment by wdvxdr1123** [comment]
是， silk格式24k采样率是目前可以全平台播放的方案

**Comment by eric2788** [comment]
好，瞭解
