### ISSUE TITLE
为什么都用bytes写入，不理解

### ISSUE THREAD

**Issue by wp19991** [Mrs4s/MiraiGo#304]
client.go里面里面的代码是需要加密吗，为什么都用bytes写入写出。
想要完成用qqtoken去登录第三方网页，现在token看都看不到，全是bytes。

**Comment by wp19991** [comment]
看半天没看懂如何利用seession.token登录qq
可能是我水平还不够吧
可以分享一下登录的流程吗@Mrs4s

**Comment by Ink-33** [comment]
有没有可能这个东西不太方便解释明白

**Comment by wp19991** [comment]
想要完成用qqtoken去登录第三方网页
现在也找不到头绪开始写这个功能

**Comment by wp19991** [comment]
就是这个文件，里面还有发送数据包的代码
https://github.com/Mrs4s/MiraiGo/blob/64722799b7ab4908bf550a3408186f7f2be39e0a/client/network.go#L154

**Comment by NWYLZW** [comment]
为什么你会问为什么都用bytes写入，不理解

**Comment by wfjsw** [comment]
不用bytes难道用string吗

**Comment by wp19991** [comment]
首先我是想拿着token去直接请求登录第三方网页，然后打开seession.token，看到是二进制不是明文，就去看源码
源码里面关于登录的都是bytes，就准备看如何把bytes变成能看到的token
发现越陷越深，加上我之前没学过go语言，语法和qq的登录过程也不太清楚
然后就提出了这个问题

**Comment by wp19991** [comment]
既然这个token可以快速登录，能不能单独独立出来，可以用其他语言带着token去请求网页

**Comment by NWYLZW** [comment]
https://github.com/Mrs4s/MiraiGo/issues/304#issuecomment-1324688893

**Comment by wfjsw** [comment]
不能

**Comment by wfjsw** [comment]
你为啥觉得这个token可以登录网页

**Comment by wp19991** [comment]
和这个项目依赖的项目有一个未实现的接口，没有实现的原因也是因为这个token不能去登录网页？
/get_cookies

**Comment by abrahum** [comment]
这个token你的q退出后重开时用的，和你网页登录的授权完全不是一个东西

**Comment by wp19991** [comment]
但是在普通的电脑上登录qq后，打开第三方网页可以不需要登录点击头像完成网页登录的授权
这个功能应该只有qq自己人才能写了
我之前隐约的注意到远程桌面的时候不能点击头像完成网页登录的授权
