### ISSUE TITLE
MiraiGo 支持QQ 的自定义分享吗

### ISSUE THREAD

**Issue by TeemoKill** [Mrs4s/MiraiGo#306]
<img width="261" alt="Screenshot 2022-12-14 at 9 30 08 PM" src="https://user-images.githubusercontent.com/39964236/207608733-3d38da50-81ef-4525-9e3d-2b7b574ac35a.png">
如题，像是这样的自定义分享卡片，可以通过MiraiGo 发送吗

**Comment by Star-Vk** [comment]
#307
