### ISSUE TITLE
首次启动，遇到Protocol -> decrypt payload error: unknown flag

### ISSUE THREAD

**Issue by AliceMandy10086** [Mrs4s/MiraiGo#308]
![屏幕截图 2022-12-27 134314](https://user-images.githubusercontent.com/113693615/209617414-f352d4de-d573-4a58-ab1e-b3fcde0663f6.png)

**Comment by Mrs4s** [comment]
更新

**Comment by AliceMandy10086** [comment]
我更新了最新，但是那个版本号还没变
