### ISSUE TITLE
消息到达问题。出现消息发送提示成功，但是 qq 界面，macOS 桌面版，ios 手机客户端，没看到的情况

### ISSUE THREAD

**Issue by af913337456** [Mrs4s/MiraiGo#317]
消息到达问题。出现消息发送提示成功，但是 qq 界面，macOS 桌面版，ios 手机客户端，没看到的情况。
1. 一方能看到，一方没；
2. 双方都没看到；
3. 换个设备又能看到

同：https://github.com/Mrs4s/go-cqhttp/issues/1927

**Comment by af913337456** [comment]
@LXY1226 @tengattack @Yukari316 @wfjsw

**Comment by LXY1226** [comment]
你问的好啊，这是为什么呢

**Comment by Yukari316** [comment]
你问的好啊，小编也不知道为什么呢

**Comment by Ink-33** [comment]
不请自来，就不谢邀了
小编觉得只要有一个人能看到，那就是确实发送成功了
