### ISSUE TITLE
qrCode登录失败：该APP尚未开通扫描二维码登录的权限。

### ISSUE THREAD

**Issue by icey-yu** [Mrs4s/MiraiGo#326]
因为使用账号密码Login产生了 `SliderNeededError` 的错误，所以使用扫码登录，但是扫码之后显示：
**登录失败，该APP尚未开通扫描二维码登录的权限。**

Mirai版本：v0.0.0-20230315231550-b461f356a30a
运行环境：win64
使用协议：所有协议都尝试过
重现步骤：使用`FetchQRCode`方法，保存图片并扫描二维码。
代码：
```go
func TestA(t *testing.T) {
	bot := client.NewClient(xxxx, "xxxx")
	bot.UseDevice(client.GenRandomDevice())
	bot.Device().Protocol = client.AndroidWatch

	bot.AllowSlider = true
	res, err := bot.Login()
	if res.Error.String() != "" {
		qrCode, err := bot.FetchQRCode()
		if err != nil {
			t.Error(err)
			return
		}
		err = os.WriteFile("qrCode.png", qrCode.ImageData, 0777)
		if err != nil {
			t.Error(err)
			return
		}

		time.Sleep(time.Minute * 2)
	}
}
```
错误结果：
![image](https://user-images.githubusercontent.com/119291641/225874062-cd9a5947-e36b-4854-baf8-777c64ffac28.png)

补充说明：
如果有的话，希望能够找到该框架的使用者的讨论群聊，一起交流。

**Comment by saikaji0314** [comment]
android watch目前也无法使用token登录，报错信息为：exchange_emp failed: 15
