### ISSUE TITLE
修改IMEI随机算法

### ISSUE THREAD

**Issue by mnixry** [Mrs4s/MiraiGo#6]
根据此处代码，目前本项目IMEI是直接选取的15位随机数
https://github.com/Mrs4s/MiraiGo/blob/98a77a6cf3541bcd837891df20374fab5cc2e8dd/client/global.go#L107-L121
但是事实上IMEI并不是完全随机的，具有地区号段以及校验位，技术细节可以参考[维基百科](https://en.wikipedia.org/wiki/International_Mobile_Equipment_Identity)，具体代码实现可以参考[这篇CSDN博客](https://blog.csdn.net/fengyifei11228/article/details/45919797)

~~虽然目前看起来貌似并不影响使用的样子~~

**Comment by Mrs4s** [comment]
这部分可以优化一下. 不过TX应该不会判断这些信息.

**Comment by duhaolong0108** [comment]
现在判断了 还不给进了
