### ISSUE TITLE
当前版本过低，请先升级到手机QQ最新版本。

### ISSUE THREAD

**Issue by esrrhs** [Mrs4s/MiraiGo#61]
c := client.NewClient(xxxxx, "xxxx")
	r, err := c.Login()
	if err != nil {
		log.Fatalf("fail %s", err)
	}
	if !r.Success {
		log.Fatalf("fail %s", r.ErrorMessage)
	}
	log.Println("ok")

**Comment by Mrs4s** [comment]
此问题一般为密码错误，请参考 `go-cqhttp` 的处理流程 https://github.com/Mrs4s/go-cqhttp/blob/08b55473aa1847a446a2e23498b7279670f92244/server/apiAdmin.go#L106

**Comment by esrrhs** [comment]
还真是，感谢

**Comment by esrrhs** [comment]
另外建议搞几个demo吧。。

**Comment by Mrs4s** [comment]
这个库实现比较蛋疼 直接调用不是很好用。。 目前是打算包装一层之类的

**Comment by esrrhs** [comment]
挺好用的，这样的api很灵活
