### ISSUE TITLE
调用GenRandomDevice后提示QQ版本过低?

### ISSUE THREAD

**Issue by null-su** [Mrs4s/MiraiGo#80]
macaddress和androidId使用随机值后会提示QQ版本过低?

**Comment by null-su** [comment]
SystemDeviceInfo.Protocol = AndroidPhone， 无论设备锁开启还是关闭，只要AndroidId或MacAddress变化，都提示请使用QQ一键登录?更换其他QQ也是这个提示。

**Comment by Mrs4s** [comment]
不随机的话就不会出现？
这个问题应该是密码错误导致的

**Comment by null-su** [comment]
> 不随机的话就不会出现？
> 这个问题应该是密码错误导致的

密码没问题 不调用GenRandomDevice就能正常登录

**Comment by null-su** [comment]
我反复用默认设备信息登录 被腾讯风控了? 我借个外地QQ试试。。。。

**Comment by ainewegg** [comment]
也碰到了这个问题，我使用的是MiraiGo-template，发现是MiraiGo里的代码返回的错误，所以在这里描述issue
条件如下：

## 尝试
- 一个QQ号总共测试了3个10位号俩个，8位号一个，

- 随机设备——GenRandomDevice方法
- 确保密码和QQ邮箱都没问题
- 结果
其中一个10位号（这个号代称：小明）可以登录
其他俩个号回弹出please input captcha:..
输入后报：
`FATA[0026] login failed: 当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。  bot=internal`

然后开启8位号的设备锁，且确保密码和QQ邮箱都没问题

# 重新尝试
- 直接报：FATA[0000] login failed: 当前版本过低，请先升级到手机QQ最新版本。           bot=internal

调用miriaGO版本信息：
github.com/Mrs4s/MiraiGo v0.0.0-20201010081553-94e56eff4549 h1:i55aF/KeXMPSOupEsQZ6uSm21CbaEZsrvP+HV9Mo/NI=
github.com/Mrs4s/MiraiGo v0.0.0-20201010081553-94e56eff4549/go.mod h1:cwYPI2uq6nxNbx0nA6YuAKF1V5szSs6FPlGVLQvRUlo=

**Comment by null-su** [comment]
等待mirai那边修复吧 大概是tx干的坏事 [https://github.com/mamoe/mirai/issues/723](#723)

**Comment by Mrs4s** [comment]
> 也碰到了这个问题，我使用的是MiraiGo-template，发现是MiraiGo里的代码返回的错误，所以在这里描述issue
> 条件如下：
> 
> ## 尝试
> * QQ号总共测试了3个10位号俩个，8位号一个，
> * 随机设备——GenRandomDevice方法
> * 确保密码和QQ邮箱都没问题
> * 结果
>   其中一个10位号（这个号代称：小明）可以登录
>   其他俩个号回弹出please input captcha:..
>   输入后报：
>   `FATA[0026] login failed: 当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。  bot=internal`
> 
> 然后开启8位号的设备锁，且确保密码和QQ邮箱都没问题
> 
> # 重新尝试
> * 直接报：FATA[0000] login failed: 当前版本过低，请先升级到手机QQ最新版本。           bot=internal
> 
> 调用miriaGO版本信息：
> github.com/Mrs4s/MiraiGo v0.0.0-20201010081553-94e56eff4549 h1:i55aF/KeXMPSOupEsQZ6uSm21CbaEZsrvP+HV9Mo/NI=
> github.com/Mrs4s/MiraiGo v0.0.0-20201010081553-94e56eff4549/go.mod h1:cwYPI2uq6nxNbx0nA6YuAKF1V5szSs6FPlGVLQvRUlo=

升级下miraigo的版本 你这个版本实在太老了， 新版本对协议做了更新的

**Comment by Mrs4s** [comment]
@null-su 请尝试使用隔壁 `go-cqhttp` 登录, 看看是否有同样的异常

**Comment by null-su** [comment]
> @null-su 请尝试使用隔壁 `go-cqhttp` 登录, 看看是否有同样的异常

隔壁mirai 2.0-M1 也是这问题，只能等修复了，嘤嘤嘤

**Comment by null-su** [comment]
> @null-su 请尝试使用隔壁 `go-cqhttp` 登录, 看看是否有同样的异常
[AllowSlider = true，使用随机设备信息能出验证设备锁了](https://gitee.com/kos_null/MiraiGo/commit/3a65d05f33782f6e6d3d00234f44ffd7660bea64)
