### ISSUE TITLE
增加查询聊天历史记录功能

### ISSUE THREAD

**Issue by james5deutschland** [Mrs4s/MiraiGo#81]
手机QQ可以获取不在线的时候的聊天历史记录。考虑在miraigo加入该项功能

**Comment by Mrs4s** [comment]
群消息的话已经有了 `client.GetGroupMessages()`, 是需要好友消息的接口嘛

**Comment by james5deutschland** [comment]
嗯呐

**Comment by james5deutschland** [comment]
比如miraigo在2号登录 获取1号的好友消息 群消息

**Comment by Mrs4s** [comment]
好友历史消息会在近期加入, 群消息需要你自己计算SEQ往上爬, 不支持按天获取

**Comment by Mrs4s** [comment]
群消息已支持, 好友消息同步是VIP专属功能, 不打算做
