### ISSUE TITLE
支持设备信息自定义

### ISSUE THREAD

**Issue by Cyame** [Mrs4s/MiraiGo#9]
感谢维护，目前关于支持设备信息自定义有一点建议。

由于最近众所周知的原因风声比较紧，因此想替代原CQHTTP继续进行服务。但是初始化后发现，设备的是基于AndriodPad给出的设备信息，同时其中含有大量MiRai字段，出于隐私和安全性的考虑，想对设备进行高度自定义。

看到源码中，在[Global](https://github.com/Mrs4s/MiraiGo/blob/98a77a6cf3541bcd837891df20374fab5cc2e8dd/client/global.go)中进行了定义和生成，在[Builders](https://github.com/Mrs4s/MiraiGo/blob/771f5d491dd1d176097bff529a58631ba27a759f/client/builders.go)中进行了与QQ-Client的交互。

但是本身对通信协议和Go语言都不够熟悉，不知道可否对除了JSON中生成的字段的其他信息进行修改？
以及如果支持修改的话，有无具体格式和自定义要求/限制？

同时基于此，是否可以以本JSON作为绕过“未知设备登录”的手段？以规避设备锁等安全机制。

**Comment by Cyame** [comment]
主要是注意到源码中，在Generate时基本都是静态的生成。因此想到如果是符合安卓设备规范的其他名称是不是也可行呢？

**Comment by mnixry** [comment]
> 如果支持修改的话，有无具体格式和自定义要求/限制？

同问，我提的 #8 #6 也是基于这个需求的

**Comment by Mrs4s** [comment]
可以通过代码来修改，暴露到文件可能下个版本才会做. 


> 主要是注意到源码中，在Generate时基本都是静态的生成。因此想到如果是符合安卓设备规范的其他名称是不是也可行呢？

只要符合Android规范，任何设备信息都是可以的
